version: 2
jobs:
  buildjoba:            
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps: 
      - checkout             
      - run:
          name: Build Job A - EntryPoint
          command: |
            echo "AAA was here..."            
  j-release-build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - run:
          name: Build Job B - EntryPoint
          command: |
            echo "BBB was here...."            

workflows:
  version: 2
  untagged-build:
    jobs:
      - buildjoba
  wf-release-build:
    jobs:
      - j-release-build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
